baseurl = "4005.kebler.net"
languageCode = "en-us"
title = "For Sale: 4005 Rock Way, Central Point, OR"
canonifyUrls = "true"
staticDir ="assets"
publishDir = "dist"

[params]
  custom_css = ["css/custom.css"]
  font = "Baloo"  # a valid google font name, default Roboto

#  For List of html colors
# http://www.quackit.com/css/color/charts/css_color_names_chart.cfm

[params.navbar]
  # text = "For Sale By Owner: 4005 Rock Way"  # default is to use the page title
  text_size="1" # unit is em, 1em is default
  # font = "Ranga"
  color = "white"
  bg_color = "seagreen"

[params.hero]
  img = "../images/4005front.jpg"  # default is images/hero.jpg, must provide the full path or url
  # img_medium = "intro-medium.jpg"  # min 1024
  # img_small  "intro-small.jpg"
  font = "Acme"  # a valid google font name, default Roboto for all hero text
  # color = "green"
  # font_headline = "Gloria Hallelujah"  # a valid google font name, defaults to intro font
  headline = "For Sale"
  headline_color = "red"
  # headline_size = "10"
  subheadline = "4005 Rock Way"
  # subheadline_color = "pink"
  # subheadline_size = "1"
  subsubheadline = "Central Point, Oregon"
  # subsubheadline_color = "brown"
  # subsubheadline_size = "1"
  lines = ["A Rambler Style House","Close to Schools"]
  # lines_color = "purple"
  lines_size = "1.5"
  divider = true
  divider_color = "seagreen"
  # divider_thickness = "3"

[params.sections]
    font = "Lato"
    headline_font = "Lato"
    headline_size = "3"
    [params.sections.odd]
    # color = ""
    # bg_color = ""
    [params.sections.even]
    # color = ""
    # bg_color = ""


[[params.social]]
    title = "email"
    icon = "envelope-o"
    url = "mailto:4005@kebler.net"
